# Generated by Django 2.0.7 on 2018-07-30 05:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('sub', django.contrib.postgres.fields.jsonb.JSONField()),
                ('rel', django.contrib.postgres.fields.jsonb.JSONField()),
                ('obj', django.contrib.postgres.fields.jsonb.JSONField()),
                ('source', django.contrib.postgres.fields.jsonb.JSONField()),
                ('context', models.CharField(max_length=200)),
            ],
        ),
    ]
