# Generated by Django 2.0.7 on 2018-07-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triple',
            old_name='sub',
            new_name='sbj',
        ),
    ]
