# Generated by Django 2.0.7 on 2018-07-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcg', '0002_auto_20180730_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triple',
            options={'ordering': ('uid',)},
        ),
    ]
