# Generated by Django 2.0.7 on 2018-07-31 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcg', '0004_triple_confidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triple',
            options={'ordering': ('-confidence',)},
        ),
    ]
