# Generated by Django 2.0.7 on 2018-07-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcg', '0005_auto_20180731_1424'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='triple',
            index=models.Index(fields=['sbj'], name='kcg_triple_sbj_e478f9_idx'),
        ),
        migrations.AddIndex(
            model_name='triple',
            index=models.Index(fields=['rel'], name='kcg_triple_rel_3c046e_idx'),
        ),
        migrations.AddIndex(
            model_name='triple',
            index=models.Index(fields=['obj'], name='kcg_triple_obj_f570bd_idx'),
        ),
        migrations.AddIndex(
            model_name='triple',
            index=models.Index(fields=['-confidence'], name='kcg_triple_confide_eafbc0_idx'),
        ),
    ]
